/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 132
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 57
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 8
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_SLASH_GT = 2,
  anon_sym_GT = 3,
  anon_sym_LT_SLASH = 4,
  anon_sym_EQ = 5,
  sym_attribute_name = 6,
  anon_sym_DQUOTE = 7,
  anon_sym_SQUOTE = 8,
  sym_quoted_attribute_text = 9,
  sym_single_quoted_attribute_text = 10,
  sym_unquoted_attribute_value = 11,
  sym_tag_name = 12,
  sym_script_tag_name = 13,
  sym_style_tag_name = 14,
  sym_comment = 15,
  anon_sym_LBRACE = 16,
  anon_sym_RBRACE = 17,
  sym_text = 18,
  sym_raw_text = 19,
  sym_component_script = 20,
  sym_riot_expression_text = 21,
  sym__scss_style_tag_name = 22,
  sym__css_style_tag_name = 23,
  sym__script_start_tag_name = 24,
  sym__start_tag_name = 25,
  sym__void_start_tag_name = 26,
  sym_source_file = 27,
  sym__top_level_node = 28,
  sym_component = 29,
  sym__component_child = 30,
  sym__template_node = 31,
  sym_element = 32,
  sym_normal_element = 33,
  sym_self_closing_element = 34,
  sym_void_element = 35,
  sym_start_tag = 36,
  sym_end_tag = 37,
  sym_script_element = 38,
  sym_script_start_tag = 39,
  sym_script_end_tag = 40,
  sym__style_element = 41,
  sym_scss_style_element = 42,
  sym_css_style_element = 43,
  sym_scss_style_start_tag = 44,
  sym_css_style_start_tag = 45,
  sym_style_end_tag = 46,
  sym_attribute = 47,
  sym_attribute_value = 48,
  sym_quoted_attribute_value = 49,
  sym_riot_expression = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_component_repeat1 = 52,
  aux_sym_normal_element_repeat1 = 53,
  aux_sym_self_closing_element_repeat1 = 54,
  aux_sym_quoted_attribute_value_repeat1 = 55,
  aux_sym_quoted_attribute_value_repeat2 = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [sym_quoted_attribute_text] = "quoted_attribute_text",
  [sym_single_quoted_attribute_text] = "single_quoted_attribute_text",
  [sym_unquoted_attribute_value] = "unquoted_attribute_value",
  [sym_tag_name] = "tag_name",
  [sym_script_tag_name] = "tag_name",
  [sym_style_tag_name] = "tag_name",
  [sym_comment] = "comment",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_text] = "text",
  [sym_raw_text] = "raw_text",
  [sym_component_script] = "component_script",
  [sym_riot_expression_text] = "riot_expression_text",
  [sym__scss_style_tag_name] = "tag_name",
  [sym__css_style_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__start_tag_name] = "tag_name",
  [sym__void_start_tag_name] = "tag_name",
  [sym_source_file] = "source_file",
  [sym__top_level_node] = "_top_level_node",
  [sym_component] = "component",
  [sym__component_child] = "_component_child",
  [sym__template_node] = "_template_node",
  [sym_element] = "element",
  [sym_normal_element] = "normal_element",
  [sym_self_closing_element] = "self_closing_element",
  [sym_void_element] = "void_element",
  [sym_start_tag] = "start_tag",
  [sym_end_tag] = "end_tag",
  [sym_script_element] = "script_element",
  [sym_script_start_tag] = "script_start_tag",
  [sym_script_end_tag] = "script_end_tag",
  [sym__style_element] = "_style_element",
  [sym_scss_style_element] = "scss_style_element",
  [sym_css_style_element] = "css_style_element",
  [sym_scss_style_start_tag] = "scss_style_start_tag",
  [sym_css_style_start_tag] = "css_style_start_tag",
  [sym_style_end_tag] = "style_end_tag",
  [sym_attribute] = "attribute",
  [sym_attribute_value] = "attribute_value",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_riot_expression] = "riot_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_component_repeat1] = "component_repeat1",
  [aux_sym_normal_element_repeat1] = "normal_element_repeat1",
  [aux_sym_self_closing_element_repeat1] = "self_closing_element_repeat1",
  [aux_sym_quoted_attribute_value_repeat1] = "quoted_attribute_value_repeat1",
  [aux_sym_quoted_attribute_value_repeat2] = "quoted_attribute_value_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_quoted_attribute_text] = sym_quoted_attribute_text,
  [sym_single_quoted_attribute_text] = sym_single_quoted_attribute_text,
  [sym_unquoted_attribute_value] = sym_unquoted_attribute_value,
  [sym_tag_name] = sym_tag_name,
  [sym_script_tag_name] = sym_tag_name,
  [sym_style_tag_name] = sym_tag_name,
  [sym_comment] = sym_comment,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_text] = sym_text,
  [sym_raw_text] = sym_raw_text,
  [sym_component_script] = sym_component_script,
  [sym_riot_expression_text] = sym_riot_expression_text,
  [sym__scss_style_tag_name] = sym_tag_name,
  [sym__css_style_tag_name] = sym_tag_name,
  [sym__script_start_tag_name] = sym_tag_name,
  [sym__start_tag_name] = sym_tag_name,
  [sym__void_start_tag_name] = sym_tag_name,
  [sym_source_file] = sym_source_file,
  [sym__top_level_node] = sym__top_level_node,
  [sym_component] = sym_component,
  [sym__component_child] = sym__component_child,
  [sym__template_node] = sym__template_node,
  [sym_element] = sym_element,
  [sym_normal_element] = sym_normal_element,
  [sym_self_closing_element] = sym_self_closing_element,
  [sym_void_element] = sym_void_element,
  [sym_start_tag] = sym_start_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_script_element] = sym_script_element,
  [sym_script_start_tag] = sym_script_start_tag,
  [sym_script_end_tag] = sym_script_end_tag,
  [sym__style_element] = sym__style_element,
  [sym_scss_style_element] = sym_scss_style_element,
  [sym_css_style_element] = sym_css_style_element,
  [sym_scss_style_start_tag] = sym_scss_style_start_tag,
  [sym_css_style_start_tag] = sym_css_style_start_tag,
  [sym_style_end_tag] = sym_style_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_attribute_value] = sym_attribute_value,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_riot_expression] = sym_riot_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_component_repeat1] = aux_sym_component_repeat1,
  [aux_sym_normal_element_repeat1] = aux_sym_normal_element_repeat1,
  [aux_sym_self_closing_element_repeat1] = aux_sym_self_closing_element_repeat1,
  [aux_sym_quoted_attribute_value_repeat1] = aux_sym_quoted_attribute_value_repeat1,
  [aux_sym_quoted_attribute_value_repeat2] = aux_sym_quoted_attribute_value_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_quoted_attribute_text] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_attribute_text] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_script_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_style_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_component_script] = {
    .visible = true,
    .named = true,
  },
  [sym_riot_expression_text] = {
    .visible = true,
    .named = true,
  },
  [sym__scss_style_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__css_style_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__void_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_level_node] = {
    .visible = false,
    .named = true,
  },
  [sym_component] = {
    .visible = true,
    .named = true,
  },
  [sym__component_child] = {
    .visible = false,
    .named = true,
  },
  [sym__template_node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_normal_element] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_element] = {
    .visible = true,
    .named = true,
  },
  [sym_void_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__style_element] = {
    .visible = false,
    .named = true,
  },
  [sym_scss_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_css_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_scss_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_css_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_riot_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_component_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_normal_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_self_closing_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 14,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 15,
  [46] = 16,
  [47] = 18,
  [48] = 19,
  [49] = 49,
  [50] = 50,
  [51] = 36,
  [52] = 52,
  [53] = 53,
  [54] = 37,
  [55] = 55,
  [56] = 38,
  [57] = 39,
  [58] = 40,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 41,
  [63] = 42,
  [64] = 43,
  [65] = 44,
  [66] = 29,
  [67] = 49,
  [68] = 31,
  [69] = 32,
  [70] = 33,
  [71] = 13,
  [72] = 28,
  [73] = 34,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 35,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 20,
  [83] = 23,
  [84] = 20,
  [85] = 23,
  [86] = 20,
  [87] = 23,
  [88] = 88,
  [89] = 88,
  [90] = 90,
  [91] = 80,
  [92] = 92,
  [93] = 90,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 96,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 96,
  [108] = 108,
  [109] = 99,
  [110] = 102,
  [111] = 104,
  [112] = 96,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 114,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 114,
  [122] = 122,
  [123] = 118,
  [124] = 120,
  [125] = 125,
  [126] = 126,
  [127] = 114,
  [128] = 122,
  [129] = 119,
  [130] = 125,
  [131] = 126,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '"', 29,
        '\'', 30,
        '/', 51,
        '<', 23,
        '=', 27,
        '>', 25,
        '{', 49,
        '}', 50,
        ':', 28,
        '_', 28,
        'S', 37,
        's', 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x3000) SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '\'') ADVANCE(30);
      if (lookahead == '{') ADVANCE(49);
      if (lookahead == 0x3000) ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '}') ADVANCE(36);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '{') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x3000) ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(32);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(30);
      if (lookahead == '{') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x3000) ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == '>') ADVANCE(25);
      if (lookahead == '}') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x3000) SKIP(8);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(24);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(48);
      END_STATE();
    case 11:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(16);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 13:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 17:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x3000) SKIP(17);
      END_STATE();
    case 18:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(46);
      END_STATE();
    case 19:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(14);
      END_STATE();
    case 20:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x3000) SKIP(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 21:
      if (eof) ADVANCE(22);
      if (lookahead == '<') ADVANCE(23);
      if (lookahead == '{') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x3000) SKIP(21);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(7);
      if (lookahead == '/') ADVANCE(26);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_quoted_attribute_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x3000) ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_quoted_attribute_text);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_single_quoted_attribute_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x3000) ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_single_quoted_attribute_text);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_unquoted_attribute_value);
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '\'') ADVANCE(30);
      if (lookahead == '{') ADVANCE(49);
      if (lookahead == 0x3000) ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '}') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_unquoted_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(42);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(44);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(47);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(41);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(38);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(43);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(39);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(46);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(40);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_script_tag_name);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_style_tag_name);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '>') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(52);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 21},
  [2] = {.lex_state = 21},
  [3] = {.lex_state = 21},
  [4] = {.lex_state = 21},
  [5] = {.lex_state = 21},
  [6] = {.lex_state = 21},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 21},
  [11] = {.lex_state = 21},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 21},
  [14] = {.lex_state = 0, .external_lex_state = 3},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 21},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 21},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 21},
  [29] = {.lex_state = 21},
  [30] = {.lex_state = 0, .external_lex_state = 3},
  [31] = {.lex_state = 21},
  [32] = {.lex_state = 21},
  [33] = {.lex_state = 21},
  [34] = {.lex_state = 21},
  [35] = {.lex_state = 21},
  [36] = {.lex_state = 21},
  [37] = {.lex_state = 21},
  [38] = {.lex_state = 21},
  [39] = {.lex_state = 21},
  [40] = {.lex_state = 21},
  [41] = {.lex_state = 21},
  [42] = {.lex_state = 21},
  [43] = {.lex_state = 21},
  [44] = {.lex_state = 21},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 8},
  [48] = {.lex_state = 8},
  [49] = {.lex_state = 21},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 0, .external_lex_state = 2},
  [52] = {.lex_state = 21},
  [53] = {.lex_state = 8},
  [54] = {.lex_state = 0, .external_lex_state = 2},
  [55] = {.lex_state = 21},
  [56] = {.lex_state = 0, .external_lex_state = 2},
  [57] = {.lex_state = 0, .external_lex_state = 2},
  [58] = {.lex_state = 0, .external_lex_state = 2},
  [59] = {.lex_state = 21},
  [60] = {.lex_state = 8},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 0, .external_lex_state = 2},
  [63] = {.lex_state = 0, .external_lex_state = 2},
  [64] = {.lex_state = 0, .external_lex_state = 2},
  [65] = {.lex_state = 0, .external_lex_state = 2},
  [66] = {.lex_state = 0, .external_lex_state = 2},
  [67] = {.lex_state = 0, .external_lex_state = 2},
  [68] = {.lex_state = 0, .external_lex_state = 2},
  [69] = {.lex_state = 0, .external_lex_state = 2},
  [70] = {.lex_state = 0, .external_lex_state = 2},
  [71] = {.lex_state = 0, .external_lex_state = 2},
  [72] = {.lex_state = 0, .external_lex_state = 2},
  [73] = {.lex_state = 0, .external_lex_state = 2},
  [74] = {.lex_state = 8},
  [75] = {.lex_state = 8},
  [76] = {.lex_state = 8},
  [77] = {.lex_state = 8},
  [78] = {.lex_state = 0, .external_lex_state = 2},
  [79] = {.lex_state = 8},
  [80] = {.lex_state = 0, .external_lex_state = 4},
  [81] = {.lex_state = 8},
  [82] = {.lex_state = 8},
  [83] = {.lex_state = 8},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 3},
  [87] = {.lex_state = 3},
  [88] = {.lex_state = 0, .external_lex_state = 4},
  [89] = {.lex_state = 0, .external_lex_state = 4},
  [90] = {.lex_state = 0, .external_lex_state = 4},
  [91] = {.lex_state = 0, .external_lex_state = 4},
  [92] = {.lex_state = 8},
  [93] = {.lex_state = 0, .external_lex_state = 4},
  [94] = {.lex_state = 8},
  [95] = {.lex_state = 8},
  [96] = {.lex_state = 8, .external_lex_state = 5},
  [97] = {.lex_state = 8, .external_lex_state = 5},
  [98] = {.lex_state = 0, .external_lex_state = 4},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0, .external_lex_state = 4},
  [101] = {.lex_state = 0, .external_lex_state = 4},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0, .external_lex_state = 4},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0, .external_lex_state = 4},
  [106] = {.lex_state = 0, .external_lex_state = 4},
  [107] = {.lex_state = 8, .external_lex_state = 5},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 8, .external_lex_state = 5},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 8},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 8},
  [117] = {.lex_state = 0, .external_lex_state = 6},
  [118] = {.lex_state = 8},
  [119] = {.lex_state = 20},
  [120] = {.lex_state = 8},
  [121] = {.lex_state = 8},
  [122] = {.lex_state = 8},
  [123] = {.lex_state = 8},
  [124] = {.lex_state = 8},
  [125] = {.lex_state = 17},
  [126] = {.lex_state = 17},
  [127] = {.lex_state = 8},
  [128] = {.lex_state = 8},
  [129] = {.lex_state = 20},
  [130] = {.lex_state = 17},
  [131] = {.lex_state = 17},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_attribute_name] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
    [sym_script_tag_name] = ACTIONS(1),
    [sym_style_tag_name] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_component_script] = ACTIONS(1),
    [sym_riot_expression_text] = ACTIONS(1),
    [sym__scss_style_tag_name] = ACTIONS(1),
    [sym__css_style_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__void_start_tag_name] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(115),
    [sym__top_level_node] = STATE(10),
    [sym_component] = STATE(10),
    [sym_start_tag] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [sym_text] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_start_tag,
    STATE(67), 1,
      sym_end_tag,
    STATE(89), 1,
      sym_script_start_tag,
    STATE(90), 1,
      sym_scss_style_start_tag,
    STATE(91), 1,
      sym_css_style_start_tag,
    ACTIONS(13), 2,
      sym_comment,
      sym_text,
    STATE(28), 3,
      sym_normal_element,
      sym_self_closing_element,
      sym_void_element,
    STATE(4), 8,
      sym__template_node,
      sym_element,
      sym_script_element,
      sym__style_element,
      sym_scss_style_element,
      sym_css_style_element,
      sym_riot_expression,
      aux_sym_normal_element_repeat1,
  [44] = 11,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LT_SLASH,
    STATE(3), 1,
      sym_start_tag,
    STATE(49), 1,
      sym_end_tag,
    STATE(89), 1,
      sym_script_start_tag,
    STATE(90), 1,
      sym_scss_style_start_tag,
    STATE(91), 1,
      sym_css_style_start_tag,
    ACTIONS(19), 2,
      sym_comment,
      sym_text,
    STATE(28), 3,
      sym_normal_element,
      sym_self_closing_element,
      sym_void_element,
    STATE(5), 8,
      sym__template_node,
      sym_element,
      sym_script_element,
      sym__style_element,
      sym_scss_style_element,
      sym_css_style_element,
      sym_riot_expression,
      aux_sym_normal_element_repeat1,
  [88] = 11,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_start_tag,
    STATE(54), 1,
      sym_end_tag,
    STATE(89), 1,
      sym_script_start_tag,
    STATE(90), 1,
      sym_scss_style_start_tag,
    STATE(91), 1,
      sym_css_style_start_tag,
    ACTIONS(21), 2,
      sym_comment,
      sym_text,
    STATE(28), 3,
      sym_normal_element,
      sym_self_closing_element,
      sym_void_element,
    STATE(6), 8,
      sym__template_node,
      sym_element,
      sym_script_element,
      sym__style_element,
      sym_scss_style_element,
      sym_css_style_element,
      sym_riot_expression,
      aux_sym_normal_element_repeat1,
  [132] = 11,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LT_SLASH,
    STATE(3), 1,
      sym_start_tag,
    STATE(37), 1,
      sym_end_tag,
    STATE(89), 1,
      sym_script_start_tag,
    STATE(90), 1,
      sym_scss_style_start_tag,
    STATE(91), 1,
      sym_css_style_start_tag,
    ACTIONS(21), 2,
      sym_comment,
      sym_text,
    STATE(28), 3,
      sym_normal_element,
      sym_self_closing_element,
      sym_void_element,
    STATE(6), 8,
      sym__template_node,
      sym_element,
      sym_script_element,
      sym__style_element,
      sym_scss_style_element,
      sym_css_style_element,
      sym_riot_expression,
      aux_sym_normal_element_repeat1,
  [176] = 10,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(26), 1,
      anon_sym_LT_SLASH,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_start_tag,
    STATE(89), 1,
      sym_script_start_tag,
    STATE(90), 1,
      sym_scss_style_start_tag,
    STATE(91), 1,
      sym_css_style_start_tag,
    ACTIONS(28), 2,
      sym_comment,
      sym_text,
    STATE(28), 3,
      sym_normal_element,
      sym_self_closing_element,
      sym_void_element,
    STATE(6), 8,
      sym__template_node,
      sym_element,
      sym_script_element,
      sym__style_element,
      sym_scss_style_element,
      sym_css_style_element,
      sym_riot_expression,
      aux_sym_normal_element_repeat1,
  [217] = 11,
    ACTIONS(17), 1,
      anon_sym_LT_SLASH,
    ACTIONS(34), 1,
      anon_sym_LT,
    ACTIONS(36), 1,
      sym_comment,
    ACTIONS(38), 1,
      sym_component_script,
    STATE(2), 1,
      sym_start_tag,
    STATE(52), 1,
      sym_end_tag,
    STATE(80), 1,
      sym_css_style_start_tag,
    STATE(88), 1,
      sym_script_start_tag,
    STATE(93), 1,
      sym_scss_style_start_tag,
    STATE(72), 3,
      sym_normal_element,
      sym_self_closing_element,
      sym_void_element,
    STATE(9), 7,
      sym__component_child,
      sym_element,
      sym_script_element,
      sym__style_element,
      sym_scss_style_element,
      sym_css_style_element,
      aux_sym_component_repeat1,
  [259] = 11,
    ACTIONS(17), 1,
      anon_sym_LT_SLASH,
    ACTIONS(34), 1,
      anon_sym_LT,
    ACTIONS(40), 1,
      sym_comment,
    ACTIONS(42), 1,
      sym_component_script,
    STATE(2), 1,
      sym_start_tag,
    STATE(55), 1,
      sym_end_tag,
    STATE(80), 1,
      sym_css_style_start_tag,
    STATE(88), 1,
      sym_script_start_tag,
    STATE(93), 1,
      sym_scss_style_start_tag,
    STATE(72), 3,
      sym_normal_element,
      sym_self_closing_element,
      sym_void_element,
    STATE(7), 7,
      sym__component_child,
      sym_element,
      sym_script_element,
      sym__style_element,
      sym_scss_style_element,
      sym_css_style_element,
      aux_sym_component_repeat1,
  [301] = 9,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(49), 1,
      sym_comment,
    STATE(2), 1,
      sym_start_tag,
    STATE(80), 1,
      sym_css_style_start_tag,
    STATE(88), 1,
      sym_script_start_tag,
    STATE(93), 1,
      sym_scss_style_start_tag,
    ACTIONS(47), 2,
      sym_component_script,
      anon_sym_LT_SLASH,
    STATE(72), 3,
      sym_normal_element,
      sym_self_closing_element,
      sym_void_element,
    STATE(9), 7,
      sym__component_child,
      sym_element,
      sym_script_element,
      sym__style_element,
      sym_scss_style_element,
      sym_css_style_element,
      aux_sym_component_repeat1,
  [338] = 5,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      sym_start_tag,
    ACTIONS(54), 2,
      sym_comment,
      sym_text,
    STATE(11), 3,
      sym__top_level_node,
      sym_component,
      aux_sym_source_file_repeat1,
  [357] = 5,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 1,
      anon_sym_LT,
    STATE(8), 1,
      sym_start_tag,
    ACTIONS(61), 2,
      sym_comment,
      sym_text,
    STATE(11), 3,
      sym__top_level_node,
      sym_component,
      aux_sym_source_file_repeat1,
  [376] = 6,
    ACTIONS(64), 1,
      anon_sym_DQUOTE,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(68), 1,
      sym_unquoted_attribute_value,
    ACTIONS(70), 1,
      anon_sym_LBRACE,
    STATE(81), 1,
      sym_attribute_value,
    STATE(94), 2,
      sym_quoted_attribute_value,
      sym_riot_expression,
  [396] = 2,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(72), 5,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [407] = 5,
    ACTIONS(76), 1,
      sym__scss_style_tag_name,
    ACTIONS(78), 1,
      sym__css_style_tag_name,
    ACTIONS(80), 1,
      sym__script_start_tag_name,
    ACTIONS(82), 1,
      sym__start_tag_name,
    ACTIONS(84), 1,
      sym__void_start_tag_name,
  [423] = 4,
    ACTIONS(86), 1,
      anon_sym_SLASH_GT,
    ACTIONS(88), 1,
      anon_sym_GT,
    ACTIONS(90), 1,
      sym_attribute_name,
    STATE(18), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [437] = 4,
    ACTIONS(86), 1,
      anon_sym_SLASH_GT,
    ACTIONS(90), 1,
      sym_attribute_name,
    ACTIONS(92), 1,
      anon_sym_GT,
    STATE(19), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [451] = 3,
    ACTIONS(96), 1,
      sym_attribute_name,
    ACTIONS(94), 2,
      anon_sym_SLASH_GT,
      anon_sym_GT,
    STATE(17), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [463] = 4,
    ACTIONS(90), 1,
      sym_attribute_name,
    ACTIONS(99), 1,
      anon_sym_SLASH_GT,
    ACTIONS(101), 1,
      anon_sym_GT,
    STATE(17), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [477] = 4,
    ACTIONS(90), 1,
      sym_attribute_name,
    ACTIONS(99), 1,
      anon_sym_SLASH_GT,
    ACTIONS(103), 1,
      anon_sym_GT,
    STATE(17), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [491] = 2,
    ACTIONS(105), 1,
      anon_sym_LT,
    ACTIONS(107), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [501] = 4,
    ACTIONS(109), 1,
      anon_sym_DQUOTE,
    ACTIONS(111), 1,
      sym_quoted_attribute_text,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    STATE(24), 2,
      sym_riot_expression,
      aux_sym_quoted_attribute_value_repeat1,
  [515] = 4,
    ACTIONS(109), 1,
      anon_sym_SQUOTE,
    ACTIONS(115), 1,
      sym_single_quoted_attribute_text,
    ACTIONS(117), 1,
      anon_sym_LBRACE,
    STATE(25), 2,
      sym_riot_expression,
      aux_sym_quoted_attribute_value_repeat2,
  [529] = 2,
    ACTIONS(119), 1,
      anon_sym_LT,
    ACTIONS(121), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [539] = 4,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(123), 1,
      anon_sym_DQUOTE,
    ACTIONS(125), 1,
      sym_quoted_attribute_text,
    STATE(26), 2,
      sym_riot_expression,
      aux_sym_quoted_attribute_value_repeat1,
  [553] = 4,
    ACTIONS(117), 1,
      anon_sym_LBRACE,
    ACTIONS(123), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_single_quoted_attribute_text,
    STATE(27), 2,
      sym_riot_expression,
      aux_sym_quoted_attribute_value_repeat2,
  [567] = 4,
    ACTIONS(129), 1,
      anon_sym_DQUOTE,
    ACTIONS(131), 1,
      sym_quoted_attribute_text,
    ACTIONS(134), 1,
      anon_sym_LBRACE,
    STATE(26), 2,
      sym_riot_expression,
      aux_sym_quoted_attribute_value_repeat1,
  [581] = 4,
    ACTIONS(137), 1,
      anon_sym_SQUOTE,
    ACTIONS(139), 1,
      sym_single_quoted_attribute_text,
    ACTIONS(142), 1,
      anon_sym_LBRACE,
    STATE(27), 2,
      sym_riot_expression,
      aux_sym_quoted_attribute_value_repeat2,
  [595] = 2,
    ACTIONS(145), 1,
      anon_sym_LT,
    ACTIONS(147), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [605] = 2,
    ACTIONS(149), 1,
      anon_sym_LT,
    ACTIONS(151), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [615] = 5,
    ACTIONS(76), 1,
      sym__scss_style_tag_name,
    ACTIONS(78), 1,
      sym__css_style_tag_name,
    ACTIONS(80), 1,
      sym__script_start_tag_name,
    ACTIONS(153), 1,
      sym__start_tag_name,
    ACTIONS(155), 1,
      sym__void_start_tag_name,
  [631] = 2,
    ACTIONS(157), 1,
      anon_sym_LT,
    ACTIONS(159), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [641] = 2,
    ACTIONS(161), 1,
      anon_sym_LT,
    ACTIONS(163), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [651] = 2,
    ACTIONS(165), 1,
      anon_sym_LT,
    ACTIONS(167), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [661] = 2,
    ACTIONS(169), 1,
      anon_sym_LT,
    ACTIONS(171), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [671] = 2,
    ACTIONS(173), 1,
      anon_sym_LT,
    ACTIONS(175), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [681] = 2,
    ACTIONS(177), 1,
      anon_sym_LT,
    ACTIONS(179), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [691] = 2,
    ACTIONS(181), 1,
      anon_sym_LT,
    ACTIONS(183), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [701] = 2,
    ACTIONS(185), 1,
      anon_sym_LT,
    ACTIONS(187), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [711] = 2,
    ACTIONS(189), 1,
      anon_sym_LT,
    ACTIONS(191), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [721] = 2,
    ACTIONS(193), 1,
      anon_sym_LT,
    ACTIONS(195), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [731] = 2,
    ACTIONS(197), 1,
      anon_sym_LT,
    ACTIONS(199), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [741] = 2,
    ACTIONS(201), 1,
      anon_sym_LT,
    ACTIONS(203), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [751] = 2,
    ACTIONS(205), 1,
      anon_sym_LT,
    ACTIONS(207), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [761] = 2,
    ACTIONS(209), 1,
      anon_sym_LT,
    ACTIONS(211), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [771] = 4,
    ACTIONS(88), 1,
      anon_sym_GT,
    ACTIONS(90), 1,
      sym_attribute_name,
    ACTIONS(213), 1,
      anon_sym_SLASH_GT,
    STATE(47), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [785] = 4,
    ACTIONS(90), 1,
      sym_attribute_name,
    ACTIONS(213), 1,
      anon_sym_SLASH_GT,
    ACTIONS(215), 1,
      anon_sym_GT,
    STATE(48), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [799] = 4,
    ACTIONS(90), 1,
      sym_attribute_name,
    ACTIONS(101), 1,
      anon_sym_GT,
    ACTIONS(217), 1,
      anon_sym_SLASH_GT,
    STATE(17), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [813] = 4,
    ACTIONS(90), 1,
      sym_attribute_name,
    ACTIONS(217), 1,
      anon_sym_SLASH_GT,
    ACTIONS(219), 1,
      anon_sym_GT,
    STATE(17), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [827] = 2,
    ACTIONS(221), 1,
      anon_sym_LT,
    ACTIONS(223), 4,
      anon_sym_LT_SLASH,
      sym_comment,
      anon_sym_LBRACE,
      sym_text,
  [837] = 2,
    ACTIONS(227), 1,
      anon_sym_EQ,
    ACTIONS(225), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attribute_name,
  [846] = 2,
    ACTIONS(177), 1,
      anon_sym_LT,
    ACTIONS(179), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [855] = 2,
    ACTIONS(231), 1,
      anon_sym_LT,
    ACTIONS(229), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_text,
  [864] = 3,
    ACTIONS(90), 1,
      sym_attribute_name,
    ACTIONS(233), 1,
      anon_sym_GT,
    STATE(75), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [875] = 2,
    ACTIONS(181), 1,
      anon_sym_LT,
    ACTIONS(183), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [884] = 2,
    ACTIONS(237), 1,
      anon_sym_LT,
    ACTIONS(235), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_text,
  [893] = 2,
    ACTIONS(185), 1,
      anon_sym_LT,
    ACTIONS(187), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [902] = 2,
    ACTIONS(189), 1,
      anon_sym_LT,
    ACTIONS(191), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [911] = 2,
    ACTIONS(193), 1,
      anon_sym_LT,
    ACTIONS(195), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [920] = 2,
    ACTIONS(241), 1,
      anon_sym_LT,
    ACTIONS(239), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_text,
  [929] = 3,
    ACTIONS(90), 1,
      sym_attribute_name,
    ACTIONS(243), 1,
      anon_sym_GT,
    STATE(76), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [940] = 3,
    ACTIONS(90), 1,
      sym_attribute_name,
    ACTIONS(245), 1,
      anon_sym_GT,
    STATE(77), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [951] = 2,
    ACTIONS(197), 1,
      anon_sym_LT,
    ACTIONS(199), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [960] = 2,
    ACTIONS(201), 1,
      anon_sym_LT,
    ACTIONS(203), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [969] = 2,
    ACTIONS(205), 1,
      anon_sym_LT,
    ACTIONS(207), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [978] = 2,
    ACTIONS(209), 1,
      anon_sym_LT,
    ACTIONS(211), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [987] = 2,
    ACTIONS(149), 1,
      anon_sym_LT,
    ACTIONS(151), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [996] = 2,
    ACTIONS(221), 1,
      anon_sym_LT,
    ACTIONS(223), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [1005] = 2,
    ACTIONS(157), 1,
      anon_sym_LT,
    ACTIONS(159), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [1014] = 2,
    ACTIONS(161), 1,
      anon_sym_LT,
    ACTIONS(163), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [1023] = 2,
    ACTIONS(165), 1,
      anon_sym_LT,
    ACTIONS(167), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [1032] = 2,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(72), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [1041] = 2,
    ACTIONS(145), 1,
      anon_sym_LT,
    ACTIONS(147), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [1050] = 2,
    ACTIONS(169), 1,
      anon_sym_LT,
    ACTIONS(171), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [1059] = 3,
    ACTIONS(90), 1,
      sym_attribute_name,
    ACTIONS(247), 1,
      anon_sym_GT,
    STATE(79), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [1070] = 3,
    ACTIONS(90), 1,
      sym_attribute_name,
    ACTIONS(249), 1,
      anon_sym_GT,
    STATE(17), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [1081] = 3,
    ACTIONS(90), 1,
      sym_attribute_name,
    ACTIONS(251), 1,
      anon_sym_GT,
    STATE(17), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [1092] = 3,
    ACTIONS(90), 1,
      sym_attribute_name,
    ACTIONS(253), 1,
      anon_sym_GT,
    STATE(17), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [1103] = 2,
    ACTIONS(173), 1,
      anon_sym_LT,
    ACTIONS(175), 3,
      sym_component_script,
      anon_sym_LT_SLASH,
      sym_comment,
  [1112] = 3,
    ACTIONS(90), 1,
      sym_attribute_name,
    ACTIONS(255), 1,
      anon_sym_GT,
    STATE(17), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [1123] = 3,
    ACTIONS(257), 1,
      anon_sym_LT_SLASH,
    ACTIONS(259), 1,
      sym_raw_text,
    STATE(70), 1,
      sym_style_end_tag,
  [1133] = 1,
    ACTIONS(261), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attribute_name,
  [1139] = 1,
    ACTIONS(107), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attribute_name,
  [1145] = 1,
    ACTIONS(121), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attribute_name,
  [1151] = 2,
    ACTIONS(107), 1,
      sym_quoted_attribute_text,
    ACTIONS(105), 2,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
  [1159] = 2,
    ACTIONS(121), 1,
      sym_quoted_attribute_text,
    ACTIONS(119), 2,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
  [1167] = 2,
    ACTIONS(107), 1,
      sym_single_quoted_attribute_text,
    ACTIONS(105), 2,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [1175] = 2,
    ACTIONS(121), 1,
      sym_single_quoted_attribute_text,
    ACTIONS(119), 2,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [1183] = 3,
    ACTIONS(263), 1,
      anon_sym_LT_SLASH,
    ACTIONS(265), 1,
      sym_raw_text,
    STATE(68), 1,
      sym_script_end_tag,
  [1193] = 3,
    ACTIONS(267), 1,
      anon_sym_LT_SLASH,
    ACTIONS(269), 1,
      sym_raw_text,
    STATE(31), 1,
      sym_script_end_tag,
  [1203] = 3,
    ACTIONS(271), 1,
      anon_sym_LT_SLASH,
    ACTIONS(273), 1,
      sym_raw_text,
    STATE(32), 1,
      sym_style_end_tag,
  [1213] = 3,
    ACTIONS(271), 1,
      anon_sym_LT_SLASH,
    ACTIONS(275), 1,
      sym_raw_text,
    STATE(33), 1,
      sym_style_end_tag,
  [1223] = 1,
    ACTIONS(277), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attribute_name,
  [1229] = 3,
    ACTIONS(257), 1,
      anon_sym_LT_SLASH,
    ACTIONS(279), 1,
      sym_raw_text,
    STATE(69), 1,
      sym_style_end_tag,
  [1239] = 1,
    ACTIONS(281), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attribute_name,
  [1245] = 1,
    ACTIONS(283), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attribute_name,
  [1251] = 2,
    ACTIONS(285), 1,
      anon_sym_RBRACE,
    ACTIONS(287), 1,
      sym_riot_expression_text,
  [1258] = 2,
    ACTIONS(289), 1,
      anon_sym_RBRACE,
    ACTIONS(291), 1,
      sym_riot_expression_text,
  [1265] = 1,
    ACTIONS(293), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1270] = 2,
    ACTIONS(263), 1,
      anon_sym_LT_SLASH,
    STATE(56), 1,
      sym_script_end_tag,
  [1277] = 1,
    ACTIONS(295), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1282] = 1,
    ACTIONS(297), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1287] = 2,
    ACTIONS(257), 1,
      anon_sym_LT_SLASH,
    STATE(57), 1,
      sym_style_end_tag,
  [1294] = 1,
    ACTIONS(299), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1299] = 2,
    ACTIONS(257), 1,
      anon_sym_LT_SLASH,
    STATE(58), 1,
      sym_style_end_tag,
  [1306] = 1,
    ACTIONS(301), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1311] = 1,
    ACTIONS(303), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1316] = 2,
    ACTIONS(305), 1,
      anon_sym_RBRACE,
    ACTIONS(307), 1,
      sym_riot_expression_text,
  [1323] = 2,
    ACTIONS(17), 1,
      anon_sym_LT_SLASH,
    STATE(59), 1,
      sym_end_tag,
  [1330] = 2,
    ACTIONS(267), 1,
      anon_sym_LT_SLASH,
    STATE(38), 1,
      sym_script_end_tag,
  [1337] = 2,
    ACTIONS(271), 1,
      anon_sym_LT_SLASH,
    STATE(39), 1,
      sym_style_end_tag,
  [1344] = 2,
    ACTIONS(271), 1,
      anon_sym_LT_SLASH,
    STATE(40), 1,
      sym_style_end_tag,
  [1351] = 2,
    ACTIONS(309), 1,
      anon_sym_RBRACE,
    ACTIONS(311), 1,
      sym_riot_expression_text,
  [1358] = 2,
    ACTIONS(17), 1,
      anon_sym_LT_SLASH,
    STATE(52), 1,
      sym_end_tag,
  [1365] = 1,
    ACTIONS(313), 1,
      anon_sym_RBRACE,
  [1369] = 1,
    ACTIONS(315), 1,
      ts_builtin_sym_end,
  [1373] = 1,
    ACTIONS(317), 1,
      anon_sym_RBRACE,
  [1377] = 1,
    ACTIONS(319), 1,
      sym__start_tag_name,
  [1381] = 1,
    ACTIONS(321), 1,
      anon_sym_GT,
  [1385] = 1,
    ACTIONS(323), 1,
      sym_tag_name,
  [1389] = 1,
    ACTIONS(325), 1,
      anon_sym_GT,
  [1393] = 1,
    ACTIONS(327), 1,
      anon_sym_RBRACE,
  [1397] = 1,
    ACTIONS(329), 1,
      anon_sym_GT,
  [1401] = 1,
    ACTIONS(331), 1,
      anon_sym_GT,
  [1405] = 1,
    ACTIONS(333), 1,
      anon_sym_GT,
  [1409] = 1,
    ACTIONS(335), 1,
      sym_script_tag_name,
  [1413] = 1,
    ACTIONS(337), 1,
      sym_style_tag_name,
  [1417] = 1,
    ACTIONS(339), 1,
      anon_sym_RBRACE,
  [1421] = 1,
    ACTIONS(341), 1,
      anon_sym_GT,
  [1425] = 1,
    ACTIONS(343), 1,
      sym_tag_name,
  [1429] = 1,
    ACTIONS(345), 1,
      sym_script_tag_name,
  [1433] = 1,
    ACTIONS(347), 1,
      sym_style_tag_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 88,
  [SMALL_STATE(5)] = 132,
  [SMALL_STATE(6)] = 176,
  [SMALL_STATE(7)] = 217,
  [SMALL_STATE(8)] = 259,
  [SMALL_STATE(9)] = 301,
  [SMALL_STATE(10)] = 338,
  [SMALL_STATE(11)] = 357,
  [SMALL_STATE(12)] = 376,
  [SMALL_STATE(13)] = 396,
  [SMALL_STATE(14)] = 407,
  [SMALL_STATE(15)] = 423,
  [SMALL_STATE(16)] = 437,
  [SMALL_STATE(17)] = 451,
  [SMALL_STATE(18)] = 463,
  [SMALL_STATE(19)] = 477,
  [SMALL_STATE(20)] = 491,
  [SMALL_STATE(21)] = 501,
  [SMALL_STATE(22)] = 515,
  [SMALL_STATE(23)] = 529,
  [SMALL_STATE(24)] = 539,
  [SMALL_STATE(25)] = 553,
  [SMALL_STATE(26)] = 567,
  [SMALL_STATE(27)] = 581,
  [SMALL_STATE(28)] = 595,
  [SMALL_STATE(29)] = 605,
  [SMALL_STATE(30)] = 615,
  [SMALL_STATE(31)] = 631,
  [SMALL_STATE(32)] = 641,
  [SMALL_STATE(33)] = 651,
  [SMALL_STATE(34)] = 661,
  [SMALL_STATE(35)] = 671,
  [SMALL_STATE(36)] = 681,
  [SMALL_STATE(37)] = 691,
  [SMALL_STATE(38)] = 701,
  [SMALL_STATE(39)] = 711,
  [SMALL_STATE(40)] = 721,
  [SMALL_STATE(41)] = 731,
  [SMALL_STATE(42)] = 741,
  [SMALL_STATE(43)] = 751,
  [SMALL_STATE(44)] = 761,
  [SMALL_STATE(45)] = 771,
  [SMALL_STATE(46)] = 785,
  [SMALL_STATE(47)] = 799,
  [SMALL_STATE(48)] = 813,
  [SMALL_STATE(49)] = 827,
  [SMALL_STATE(50)] = 837,
  [SMALL_STATE(51)] = 846,
  [SMALL_STATE(52)] = 855,
  [SMALL_STATE(53)] = 864,
  [SMALL_STATE(54)] = 875,
  [SMALL_STATE(55)] = 884,
  [SMALL_STATE(56)] = 893,
  [SMALL_STATE(57)] = 902,
  [SMALL_STATE(58)] = 911,
  [SMALL_STATE(59)] = 920,
  [SMALL_STATE(60)] = 929,
  [SMALL_STATE(61)] = 940,
  [SMALL_STATE(62)] = 951,
  [SMALL_STATE(63)] = 960,
  [SMALL_STATE(64)] = 969,
  [SMALL_STATE(65)] = 978,
  [SMALL_STATE(66)] = 987,
  [SMALL_STATE(67)] = 996,
  [SMALL_STATE(68)] = 1005,
  [SMALL_STATE(69)] = 1014,
  [SMALL_STATE(70)] = 1023,
  [SMALL_STATE(71)] = 1032,
  [SMALL_STATE(72)] = 1041,
  [SMALL_STATE(73)] = 1050,
  [SMALL_STATE(74)] = 1059,
  [SMALL_STATE(75)] = 1070,
  [SMALL_STATE(76)] = 1081,
  [SMALL_STATE(77)] = 1092,
  [SMALL_STATE(78)] = 1103,
  [SMALL_STATE(79)] = 1112,
  [SMALL_STATE(80)] = 1123,
  [SMALL_STATE(81)] = 1133,
  [SMALL_STATE(82)] = 1139,
  [SMALL_STATE(83)] = 1145,
  [SMALL_STATE(84)] = 1151,
  [SMALL_STATE(85)] = 1159,
  [SMALL_STATE(86)] = 1167,
  [SMALL_STATE(87)] = 1175,
  [SMALL_STATE(88)] = 1183,
  [SMALL_STATE(89)] = 1193,
  [SMALL_STATE(90)] = 1203,
  [SMALL_STATE(91)] = 1213,
  [SMALL_STATE(92)] = 1223,
  [SMALL_STATE(93)] = 1229,
  [SMALL_STATE(94)] = 1239,
  [SMALL_STATE(95)] = 1245,
  [SMALL_STATE(96)] = 1251,
  [SMALL_STATE(97)] = 1258,
  [SMALL_STATE(98)] = 1265,
  [SMALL_STATE(99)] = 1270,
  [SMALL_STATE(100)] = 1277,
  [SMALL_STATE(101)] = 1282,
  [SMALL_STATE(102)] = 1287,
  [SMALL_STATE(103)] = 1294,
  [SMALL_STATE(104)] = 1299,
  [SMALL_STATE(105)] = 1306,
  [SMALL_STATE(106)] = 1311,
  [SMALL_STATE(107)] = 1316,
  [SMALL_STATE(108)] = 1323,
  [SMALL_STATE(109)] = 1330,
  [SMALL_STATE(110)] = 1337,
  [SMALL_STATE(111)] = 1344,
  [SMALL_STATE(112)] = 1351,
  [SMALL_STATE(113)] = 1358,
  [SMALL_STATE(114)] = 1365,
  [SMALL_STATE(115)] = 1369,
  [SMALL_STATE(116)] = 1373,
  [SMALL_STATE(117)] = 1377,
  [SMALL_STATE(118)] = 1381,
  [SMALL_STATE(119)] = 1385,
  [SMALL_STATE(120)] = 1389,
  [SMALL_STATE(121)] = 1393,
  [SMALL_STATE(122)] = 1397,
  [SMALL_STATE(123)] = 1401,
  [SMALL_STATE(124)] = 1405,
  [SMALL_STATE(125)] = 1409,
  [SMALL_STATE(126)] = 1413,
  [SMALL_STATE(127)] = 1417,
  [SMALL_STATE(128)] = 1421,
  [SMALL_STATE(129)] = 1425,
  [SMALL_STATE(130)] = 1429,
  [SMALL_STATE(131)] = 1433,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_normal_element_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_normal_element_repeat1, 2, 0, 0),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_normal_element_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_normal_element_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(117),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 1),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 1),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_self_closing_element_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_self_closing_element_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_riot_expression, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_riot_expression, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_riot_expression, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_riot_expression, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [134] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2, 0, 0),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2, 0, 0), SHIFT_REPEAT(27),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2, 0, 0), SHIFT_REPEAT(97),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 1),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scss_style_element, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scss_style_element, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_css_style_element, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_css_style_element, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 1),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 1),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_element, 3, 0, 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_element, 3, 0, 1),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_void_element, 3, 0, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_void_element, 3, 0, 1),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_normal_element, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_normal_element, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scss_style_element, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scss_style_element, 3, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_css_style_element, 3, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_css_style_element, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_element, 4, 0, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_element, 4, 0, 1),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_void_element, 4, 0, 1),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_void_element, 4, 0, 1),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_end_tag, 3, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_end_tag, 3, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_end_tag, 3, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_end_tag, 3, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_normal_element, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_normal_element, 2, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 3, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 3, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 2, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 2, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 4, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 4, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 1, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scss_style_start_tag, 3, 0, 1),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_css_style_start_tag, 3, 0, 1),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scss_style_start_tag, 4, 0, 1),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_css_style_start_tag, 4, 0, 1),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4, 0, 1),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3, 0, 1),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [315] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_raw_text = 0,
  ts_external_token_component_script = 1,
  ts_external_token_riot_expression_text = 2,
  ts_external_token__scss_style_tag_name = 3,
  ts_external_token__css_style_tag_name = 4,
  ts_external_token__script_start_tag_name = 5,
  ts_external_token__start_tag_name = 6,
  ts_external_token__void_start_tag_name = 7,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_component_script] = sym_component_script,
  [ts_external_token_riot_expression_text] = sym_riot_expression_text,
  [ts_external_token__scss_style_tag_name] = sym__scss_style_tag_name,
  [ts_external_token__css_style_tag_name] = sym__css_style_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__void_start_tag_name] = sym__void_start_tag_name,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_component_script] = true,
    [ts_external_token_riot_expression_text] = true,
    [ts_external_token__scss_style_tag_name] = true,
    [ts_external_token__css_style_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__void_start_tag_name] = true,
  },
  [2] = {
    [ts_external_token_component_script] = true,
  },
  [3] = {
    [ts_external_token__scss_style_tag_name] = true,
    [ts_external_token__css_style_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__void_start_tag_name] = true,
  },
  [4] = {
    [ts_external_token_raw_text] = true,
  },
  [5] = {
    [ts_external_token_riot_expression_text] = true,
  },
  [6] = {
    [ts_external_token__start_tag_name] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_riot_v3_external_scanner_create(void);
void tree_sitter_riot_v3_external_scanner_destroy(void *);
bool tree_sitter_riot_v3_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_riot_v3_external_scanner_serialize(void *, char *);
void tree_sitter_riot_v3_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_riot_v3(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_riot_v3_external_scanner_create,
      tree_sitter_riot_v3_external_scanner_destroy,
      tree_sitter_riot_v3_external_scanner_scan,
      tree_sitter_riot_v3_external_scanner_serialize,
      tree_sitter_riot_v3_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "riot_v3",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
